spring.application.name=mcq-platform-api

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mcq_platform_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring.devtools.restart.enabled=false

# # Dummy Data Insertion by sql
# spring.sql.init.mode=always
# spring.jpa.defer-datasource-initialization=true
